### ISSUE TITLE
haproxy metrics exposed by defaultBackend by ingress

### ISSUE THREAD

**Issue by buker** [haproxy-ingress/charts#30] opened 2021-08-17 18:23 UTC
I have issue that metrics of haproxy or haproxy-ingress are exposed to ingress on path /metrics. They shouldn't be exposed external by defaultBackend.

Values:
```
  defaultBackend:
    enabled: true
    resources:
      limits:
        cpu: 20m
        memory: 20Mi
      requests:
        cpu: 20m
        memory: 20Mi
    replicaCount: 2
  controller:
    haproxy:
      enabled: enabled
      image:
        repository: haproxy
        tag: "2.3.12"
        pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 2
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 128Mi
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 50
    serviceMonitor:
      enabled: true
    ingressClass: haproxy
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "10254"
          topologyKey: "kubernetes.io/hostname"
    extraArgs:
      publish-service: "haproxy-ingress/haproxy-ingress"
    securityContext:
      sysctls:
      - name: net.ipv4.ip_local_port_range
        value: "1024 65535"
    livenessProbe:
      failureThreshold: 10
    service:
      type: LoadBalancer  
      labels:
        app.kubernetes.io/release: haproxy-ingress
    stats:
      enabled: true
    metrics:
      enabled: true
      embaded: false
    config:
      timeout-keep-alive: 620s
      config-global: |
        tune.bufsize 32768
        tune.maxrewrite 8192
      config-defaults: |
        option redispatch
      securityContext:
        privileged: true
```

Metrics are available on 

http://ingress-domain.com/metrics

When ingress object has defined path /metrics it will display app metrics

**Comment by jcmoraisjr** [comment] 2021-08-22 18:19
Hi thanks for sharing this. The problem is the default image which has a `/metrics` uri, I'll look for another image and change the default option.

Since you're not using your own email, it should be safe to change defaultBackend/enabled to false or even remove the whole defaultBackend config - HAProxy Ingress has its own self generated 404 error page which doesn't have this problem.

**Comment by jcmoraisjr** [comment] 2021-08-29 01:26
Default image updated to `k8s.gcr.io/defaultbackend-amd64:1.5`, which doesn't implement a `/metrics` uri, and will be available in the next release. Closing.

**Closed by jcmoraisjr** 2021-08-29 01:26 UTC
Labels: enhancement
